#!/bin/bash
#Define senha do Sudo
senha_sudo="digite aqui a sua senha"
echo ""
echo "Instalando o ohmyzsh"
echo $senha_sudo | sudo -S sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
echo ""
echo "Instalando o plugin syntax-highlighting"
sudo git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
echo ""
echo "Instalando o plugin autosuggestions"
sudo git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
echo ""
echo "Baixando e instalando o plugin fzf"
sudo git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && sudo ~/.fzf/install
echo ""
echo "Instalando o plugin K"
sudo git clone https://github.com/supercrabtree/k $ZSH_CUSTOM/plugins/k
echo ""
echo "Instalações efetuadas"


